name: Cypress Tests

on:
  push:

  workflow_dispatch:

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Cypress run component tests
      uses: cypress-io/github-action@v5.8.2
      with:
        component: true